<?php

namespace Simettric\SimpleForumBundle\Repository;

/**
 * PostReplyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostReplyRepository extends \Doctrine\ORM\EntityRepository
{
}
